Added getblockchainsyncstatus check and Node Just started
cryon-io/ami.tent.node pull request #4
Opened 2020-12-20 23:41 UTC by ciripel

2020-12-21 20:50 UTC, cryi requested changes
Just remove mentioned assignment please. 

*This can be merged only after new daemon is released.*

2020-12-21 20:50 UTC, cryi commented on src/__xsg/info.lua
> +                    _info.level = "ok"
`_info.level` has to be set to `ok` only once and that is before any of checks happen. (It `ok` by default.) So not here 🙂

2020-12-21 21:00 UTC, cryi commented on src/__xsg/info.lua
> +                    _info.level = "ok"
Please remove others `_info.level = "ok"` after this one as well.

2020-12-22 19:46 UTC, ciripel commented
Resolved

2020-12-25 18:06 UTC, cryi commented
Thank you 🙂

2020-12-25 18:07 UTC, merged